#
# Module manifest for module 'MASES.NetPDFPS'
#
# Generated by: MASES s.r.l.
#

@{

RootModule = 'MASES.NetPDFPS.psm1'

ModuleVersion = '3.0.2'

CompatiblePSEditions = 'Desktop', 'Core'

GUID = '579EB835-AF47-49CD-9D0C-E5A3F13AA176'

Author = 'MASES s.r.l.'

CompanyName = 'MASES s.r.l.'

Copyright = 'Copyright ©  MASES s.r.l. 2025'

Description = 'NetPDF (.NET suite for PDFBox™) PowerShell (aka NetPDFPS) is a PowerShell Module to use PDFBox™ and PowerShell side-by-side. With NetPDFPS it is possible to:
- create and use PDFBox™ objects from PowerShell: initialize PDFBox™ object (Java, Scala, Kotlin, ...), execute methods on the object, read data from the object to be used for further PowerShell code 
- send to JVM objects data managed from PowerShell: e.g. data of PowerShell, like an input from command-line or a variable, can be used as an argument for the initialization or execution of a method of a JVM object

More information within the project hosted on GitHub at https://github.com/masesgroup/NetPDF for further information.'

PowerShellVersion = '5.1'

# PowerShellHostName = ''

# PowerShellHostVersion = ''

# DotNetFrameworkVersion = ''

# CLRVersion = ''

# ProcessorArchitecture = ''

# RequiredModules = @()

# RequiredAssemblies = @()

# ScriptsToProcess = @()

# TypesToProcess = @()

# FormatsToProcess = @()

# NestedModules = @()

FunctionsToExport = @()

CmdletsToExport = @(
    'Start-NetPDFPS',
    'New-PDFObject',
    'Open-PDF',
    'Save-PDF'
)

VariablesToExport = '*'

AliasesToExport = @()

# DscResourcesToExport = @()

# ModuleList = @()

# FileList = @()

PrivateData = @{

    PSData = @{

        Tags = @('NetPDFPS', 'NetPDF', 'PSEdition_Core', 'PSEdition_Desktop', 'Windows', 'Linux', 'JVM', 'Java', 'PDFBox™', 'PDF', 'bridge', 'gateway')

        LicenseUri = 'https://github.com/masesgroup/NetPDF/blob/master/LICENSE'

        ProjectUri = 'https://github.com/masesgroup/NetPDF'

        IconUri = 'https://raw.githubusercontent.com/masesgroup/NetPDF/master/src/net/Common/JCOB128x128.png'

        ReleaseNotes = 'https://github.com/masesgroup/NetPDF/releases'

    }
} 

HelpInfoURI = 'https://netpdf.masesgroup.com/articles/usagePS.html'

# DefaultCommandPrefix = ''
}

